<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Pipelines\" />
    <Folder Include="Retrieval\" />
    <Folder Include="Chunking\" />
    <Folder Include="LLM\" />
    <Folder Include="Embedding\" />
  </ItemGroup>

</Project>
